### ISSUE TITLE
[Bug] In certain modes, the "attack/turbo" button doesn't fire off your weapon.

### ISSUE THREAD

**Issue by Fordi** [mmatyas/supermariowar#10]
Reproduction:
* Start a Tour mode game, single player, with bot
* On certain levels of the tour (doesn't seem to be consistent), you will be unable to, for example, shoot fireballs, hammers, or boomerangs.

**Comment by mmatyas** [comment]
This should be fixed in alpha5, please test if these bugs still happen.

**Comment by Fordi** [comment]
Thanks.  Appears to be fixed on master.
