### ISSUE TITLE
Stomp mode game crash

### ISSUE THREAD

**Issue by AzureBerylBlue** [mmatyas/supermariowar#118]
I noticed the game would sometimes crash during stomp mode, and I was able to create a tour that crashes the game 100% of the time.
[CrashTour.zip](https://github.com/mmatyas/supermariowar/files/3829034/CrashTour.zip)

**Comment by mmatyas** [comment]
It seems the code tries to access an invalid map block when an eyecandy is updated. At `src/common/eyecandy.cpp:416`, there is a case where either leftblock or rightblock becomes an invalid pointer because g_map->block() that creates them is called with out of range parameters.
