### ISSUE TITLE
Unused files in the data folder zip

### ISSUE THREAD

**Issue by AzureBerylBlue** [mmatyas/supermariowar#135]
- data\gfx\packs\Classic\hazards\Copy of rotodisc.png (3 files)
- data\gfx\docs (The entire folder. The docs was moved [here](https://github.com/mmatyas/supermariowar/tree/master/docs).)
- data\scripts (The entire folder is unused.)
- data\gfx\packs\menu\splash_72dpi.png and splash_contest_winners.png (The code that loads these is commented out.)

**Comment by mmatyas** [comment]
`data/scripts` seems to be used in debug mode, but I can clean up the rest.
