### ISSUE TITLE
Failed Raspberry Pi build

### ISSUE THREAD

**Issue by HerbFargus** [mmatyas/supermariowar#14]
http://pastebin.com/85DtuTiu

happens as of commit d9d2299e09049b53c4bac7fe8b1e558132cf3a1a

How's travis looking now ;)

**Comment by Ronoh55** [comment]
Lines 31-37 of the pastebin reference the file changed in the commit mentioned above. I also got this error.

**Comment by HerbFargus** [comment]
submitted pull request: https://github.com/mmatyas/supermariowar/pull/15

**Comment by mmatyas** [comment]
Merged #15, thanks!
