### ISSUE TITLE
SMW Level Editor Bug - Black Space is Placing the Blocks Randomly

### ISSUE THREAD

**Issue by Magirus-Deutz** [mmatyas/supermariowar#145]
If SMW Level Editor is full screen, then black space on corner is placing the blocks randomly
Example: https://youtu.be/4YBlswzecLM

**Comment by mmatyas** [comment]
I think this issue should be fixed by now, but let me know if you still run into it!

**Comment by Magirus-Deutz** [comment]
yea, right and left is fixed but up and down still same
