### ISSUE TITLE
How do I make a server?

### ISSUE THREAD

**Issue by BULL3TB0T** [mmatyas/supermariowar#148]
Which port and which tunnel? Can somebody help me for making a server and can someone send me a server configuration file?

**Comment by mmatyas** [comment]
Hi, the game and the server program use UDP ports 12521-1252; if you're playing over the internet you should forward these two in your router to the PC that will run the server program (only one player has to do this). If that's done, you can launch `smw-server`, which should work out of the box. Players can join to the server from the game by the IP address of the PC running `smw-server`. Just note that netplay is far from perfect at the moment :)

**Comment by BULL3TB0T** [comment]
@mmatyas i can't put an ":" in the Add/Remove servers section. How do i do that? I'm trying to connect with ngrok but i can't. Oh nevermind it's udp. Can you use hamachi?

**Comment by mmatyas** [comment]
At the moment the port cannot be changed (ie. you don't have to enter it). The game has UDP networking only, it *might* work with Hamachi but it wasn't really tested.

This thread might have some more details too: http://72dpiarmy.supersanctuary.net/index.php?topic=9353.msg202402#msg202402, and there's also a Youtube video of a network session on the last page.

PS. Helló! :) Na de akkor látod az órát, ha nem nagy gond, én most alszom egyet :)

**Comment by BULL3TB0T** [comment]
Thanks.

És jó alvást xd

**Comment by BULL3TB0T** [comment]
Még egy kérdés @mmatyas . Hogy lehet az empty player helyeken botokat tenni? Fogsz betenni egy olyan funkciót? Vagy már alapból benne van?

**Comment by mmatyas** [comment]
Botokat még nem lehet berakni, de ha jól emlékszem a team választásnak működnie kellene. Sajnos jelenleg senki sem dolgozik tényleg aktívan a játékon, úgyhogy új funkciók elég lassan jönnek :(

**Comment by BULL3TB0T** [comment]
Ja senki nem akar velem játszani mert azt mondják hogy "gáz a játék, meg csúszik a játékos" vagy valami akkor a netem volt.
