### ISSUE TITLE
Pink to transparent not always working.

### ISSUE THREAD

**Issue by AzureBerylBlue** [mmatyas/supermariowar#159]
The shattered ice shard show it's pink parts. From this video:
https://www.youtube.com/watch?v=gZErutWbWBc

For some reason, resaving icecube.png by copying the same exact image into a new png file fixes the bug. Here is the fixed image.

![icecube](https://user-images.githubusercontent.com/53104010/85499868-6add9700-b5b0-11ea-8174-cfb0c4a0df19.png)

**Comment by mmatyas** [comment]
Hm really interesting, checked the icecube with a hex editor, but I don't see any significant differences either. Weird.

**Comment by mmatyas** [comment]
(Fixed by #160)
