### ISSUE TITLE
Adding SDL Mixer X support

### ISSUE THREAD

**Issue by AzureBerylBlue** [mmatyas/supermariowar#162]
Ganbare-Lucifer suggested this on Discord. There is a fork of SDL Mixer called SDL Mixer X, which supports more file types, and would allow these file types to be used in music packs in SMW.
https://wohlsoft.github.io/SDL-Mixer-X/SDL_mixer_ext.html

**Comment by mmatyas** [comment]
I wonder if it fixes #114?

**Comment by Ganbare-Lucifer** [comment]
It not only does wonders like this, it also lets music loop properly if a code to set looping samples is set for .OGG

**Comment by mmatyas** [comment]
Could someone try this build, and see if all sound and music plays fine? https://github.com/mmatyas/supermariowar/releases/download/continuous/experimental_supermariowar_2020-09-01_windows.zip

**Comment by AzureBerylBlue** [comment]
Works fine for me. I made an SPC music pack you can test with.
[Standard-SPC.zip](https://github.com/mmatyas/supermariowar/files/5159257/Standard-SPC.zip)

**Comment by mmatyas** [comment]
Ok, this is now enabled in the continuous Windows builds!
