### ISSUE TITLE
SMB1 Tileset mistake (minor issue)

### ISSUE THREAD

**Issue by TheDream64** [mmatyas/supermariowar#164]
"Ganbare-Lucifer#7595" from Discord told me about this. The blue "gradient" tiles at the right are wrong because the second from last is 17 x 16 and the last is 15 x 16. I fixed this and attached the files here so it can be included next release (whenever that is). Minor issue but it still counts.

![small](https://user-images.githubusercontent.com/63875552/90683811-d15cf980-e26f-11ea-8240-d2bae060cf42.png)
![medium](https://user-images.githubusercontent.com/63875552/90683816-d28e2680-e26f-11ea-9d0e-8958840d8972.png)
![large](https://user-images.githubusercontent.com/63875552/90683813-d1f59000-e26f-11ea-98cf-4669e24b392b.png)

**Comment by mmatyas** [comment]
Hi, could you describe in more detail what the original issue is, in which files and what was changed in them? The attached images are almost 1:1 identical to the files we currently have under `data/gfx/packs/Classic/tilesets/SMB1/`. Or did you mean some other file?

**Comment by TheDream64** [comment]
You're probably gonna laugh when you see this but...
![image](https://user-images.githubusercontent.com/63875552/90715512-21a97b00-e2b3-11ea-9ad3-76c1ab81e80b.png)

That's the mistake. Left is slightly larger than normal and right is slightly smaller. That's the only problem and that's all I fixed.

**Comment by mmatyas** [comment]
Ah I see now! Thanks, will add them in a moment.

**Comment by mmatyas** [comment]
Ok, a new continuous build is on its way, should be online in about an hour.
