### ISSUE TITLE
Music Enhancement

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [mmatyas/supermariowar#170]
The All-Stars music is poor quality ripped. So I've made an enhanced Standard music pack with high quality and extra songs from Mario Maker by Ladiesman.

You can remove the extra songs if you want, the only thing that matters is the quality rip revision.

http://www.mediafire.com/file/3cu20s04c4hx3dx/Enhanced_Standard.zip/file
http://www.mediafire.com/file/q8hdehrgkgihbkj/World+Enhanced+Standard.zip/file

**Comment by mmatyas** [comment]
It seems the game just plays the last one on the list, so it's not like a hard bug. Perhaps we could add support for multiple songs in the future?

**Comment by mmatyas** [comment]
Then if there are no more issues, I'll see if I can merge https://github.com/mmatyas/supermariowar-data/pull/1 later today.

**Comment by mmatyas** [comment]
Aand merged!
