### ISSUE TITLE
Poison mushrooms always have weight in ? blocks

### ISSUE THREAD

**Issue by TheDream64** [mmatyas/supermariowar#171]
You can set the weight of items that come out of a ? block to make some more or less common or to remove possible items entirely. For some reason, poison mushrooms always have a weight, even when set to 0, which means they always have a chance of appearing. Just some info, the ? blocks I used to test this all had 1 item with a weight of 10 (max), so perhaps only having 1 item is the cause of the issue.

**Comment by mmatyas** [comment]
Ok, should be now fixed by #173.

**Comment by mmatyas** [comment]
Closing the issue, but feel free to report if this occurs again!
