### ISSUE TITLE
how to run your own server ?

### ISSUE THREAD

**Issue by sokoow** [mmatyas/supermariowar#181]
Hiya. Great project, respect. I'm trying to run my own server but.. there's no docs :/ Is there a sample of server config somewhere ?

**Comment by mmatyas** [comment]
Hi! [Here's the default config](https://raw.githubusercontent.com/mmatyas/supermariowar/master/src/server/serverconfig), you can just place the file next to the server exe and it should load the settings.

**Comment by sokoow** [comment]
cool @mmatyas -  it'd be probably useful to make it a file in the repo to make it easier for people to find it and avoid such questions ;) One more minor question - as far as noticed, network access in emscripten is still work in progress and doesn't work right ?

**Comment by mmatyas** [comment]
Sorry for the late reply! Yes, a documentation would be certainly useful, will see if I can write up one. For the emscripten port, network is disabled: it didn't really work well back when the initial porting was done, but that might have changed since then.

**Comment by mmatyas** [comment]
A bit late, but I just added some related documentation here: https://github.com/mmatyas/supermariowar/blob/master/docs/netplay.md
