### ISSUE TITLE
how can i play it on Emuelec for S905 ？

### ISSUE THREAD

**Issue by qacjava** [mmatyas/supermariowar#182]
may i ask how can i play it on Emuelec for S905 ？
冒昧请问我怎么样在我的S905机顶盒中的Emuelec系统上玩这个？

**Comment by mmatyas** [comment]
Hi, if I understand correctly, EmuELEC is a Linux based system, right? In this case, you have to compile the game from the source code; you can find the instructions for that here: https://github.com/mmatyas/supermariowar#building-instructions

If you are not experienced with building programs from source code on the S905, feel free to ask the EmuELEC developers for help!

**Comment by qacjava** [comment]
Thanks!
