### ISSUE TITLE
Game won't luanch because the game is now not supporting to Unicode Character in the folders

### ISSUE THREAD

**Issue by Magirus-Deutz** [mmatyas/supermariowar#190]
https://i.imgur.com/3FYJroX.png

There was no such problem in the old version. Now, looks like the game is not support to Unicode Character in the folders.

**Comment by mmatyas** [comment]
Thanks for the report! This should work now again in the latest version (`supermariowar_2021-04-18`); could you give it a try?

**Comment by Magirus-Deutz** [comment]
I tested and now it works. Thanks 👍
