### ISSUE TITLE
I want you to be able to disable items that extend the time.

### ISSUE THREAD

**Issue by mu60** [mmatyas/supermariowar#194]
When the mode is set to "Time Limit", items with time extension may appear, but I want to disable this.
However, when I open the item settings screen, there is no black stopwatch item.
Therefore, the time extension item cannot be disabled.
Please add it.

**Comment by TheTechRobo** [comment]
go into the game mode settings and change "Extra Time" to 0.

those aren't main items, they're only used in timed modes, so they're not in the main settings menu

**Comment by TheDream64** [comment]
on timed battles you can set the extra time to the lowest and it won't show up. Are you talking about another game mode…?

**Comment by mu60** [comment]
Thank you very much.
There was "Extra Time" in "Settings" next to "Time".

**Comment by mmatyas** [comment]
Thanks for the help everyone, I guess this can be closed then.
