### ISSUE TITLE
Controller list on screen

### ISSUE THREAD

**Issue by TheTechRobo** [mmatyas/supermariowar#202]
You know how in some games people add controller things when recording? That would be cool, if like we could turn on a list of buttons that would light up when we pressed the button on the keyboard.

**Comment by mmatyas** [comment]
Yes, I've seen such displays in video tutorials, they can be useful for following along the presentation, but what purpose would it serve directly in the game? Where should they be placed in a 4 player battle?

**Comment by TheDream64** [comment]
Yeah I don't think this is very useful. Anyways there are probably programs that can do this by themselves with an overlay and everything, adding it to the game is too much work for what it's worth

**Comment by TheDream64** [comment]
I mean you can just find em on google… this first one is just a thread of people sharing info about this
https://superuser.com/questions/248517/show-keys-pressed-in-linux
This second one is a popular one but it doesnt look that great to me
https://www.linuxuprising.com/2020/05/screenkey-is-tool-that-shows-pressed.html?m=1
This third and final one I found seems to be the best but I've heard it a bit outdated now
https://mygeekopinions.blogspot.com/2011/05/key-status-monitor-key-mon-on-screen.html?m=1

Good luck… i dont use linux :P
