### ISSUE TITLE
Unable to run it due to a wrong directory searching

### ISSUE THREAD

**Issue by Thanatermesis** [mmatyas/supermariowar#207]
Trying to run smw it exits with this error:

**ERROR: Empty directory.  /usr/games/data/gfx/packs/Classic/tilesets/**

Which the directory is totally wrong, the correct directory is /usr/**share**/games/**smw**/gfx... 

In CMakeLists.txt there's a line containing:
`    set(SMW_DATADIR ${CMAKE_INSTALL_PREFIX}/share/games/smw CACHE PATH "Installation location of the game data")
`
but seems like SMW_DATADIR is not used for this?

**Comment by TheTechRobo** [comment]
I have this same issue.. Sometimes it goes away with new package versions, I'm unsure if that's related.

(I'm using @Thanatermesis' automated packages. They rebuild every commit on master)

**Comment by Thanatermesis** [comment]
The command works, but seems like the .desktop flies has this parameter missing (it includes the address but not the --datadir part)

**Comment by mmatyas** [comment]
Ok, it should be now fixed.

**Comment by mmatyas** [comment]
I guess this fixed the issue then.

**Comment by TheTechRobo** [comment]
Yup, it did. Thanks
