### ISSUE TITLE
Flatpak for SteamDeck

### ISSUE THREAD

**Issue by SaulGoodman1337** [mmatyas/supermariowar#223]
Hi,
Would it be a lot of work for you to create a flatpak in which the libSDL dependencies are resolved?
Greetings Daniel

**Comment by mmatyas** [comment]
Hi, I don't have a Steam Deck so I wouldn't  be able to test whether it works or not. Also as the game uses assets from Mario games, I'm not sure flathub would legally allow hosting the game there.

**Comment by SaulGoodman1337** [comment]
Hi,
I can do the testing, that's no problem. 
You don't have to upload the flatpak to flathub. It is sufficient if you provide it here. 
Do you need help with that ?

**Comment by mmatyas** [comment]
Hm, I usually don't make issue-specific releases, but it sounds like you're already familiar with creating Flatpaks? If you'd like to, feel free to write one, pull requests are welcome.

**Comment by imbev** [comment]
I've created a Flatpak package - https://github.com/imbev/supermariowar-flatpak

It requires changes such as a .desktop file (needed for app menus), but can be downloaded and run.

**Comment by imbev** [comment]
![Screenshot_20230128_105154](https://user-images.githubusercontent.com/105524473/215278988-90964c81-85e7-47d3-aedf-ae893df50388.png)

**Comment by imbev** [comment]
Another issue with the flatpak is that it depends on a manually downloaded SMW. If there is a canonical Linux download url or if it is built from source, this problem would be resolved.

**Comment by mmatyas** [comment]
Nice! Yeah, building from source is probably how it's supposed to work, but as a workaround this might be useful as well.

**Comment by mmatyas** [comment]
There's now an official Flatpak nightly build at https://mmatyas.github.io/supermariowar-flatpak/. Have fun!
