### ISSUE TITLE
Tileset Limit Break

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [mmatyas/supermariowar#224]
It's annoying to see that if somehow the tileset height and width are extended, the map editor can crash.

How about break the tileset limitations in some way?

**Comment by Magirus-Deutz** [comment]
I made a video about it before and I posted it in #127 
https://youtu.be/mT1ft2eidqw

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest build!
