### ISSUE TITLE
SMB1 Tileset Fixes

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [mmatyas/supermariowar#226]
![image](https://user-images.githubusercontent.com/42012156/167930473-2e96fefd-ced6-4db6-a8c1-9b51988f0a49.png)
Left: Original, Right: My Fixes

So, I've noticed few SMB1 tiles were badly ripped, so I fixed them.

**Comment by mmatyas** [comment]
Great! Could you create a pull request at https://github.com/mmatyas/supermariowar-data with the updated images? I'm not sure if everything's still pixel perfect when posted as an image here.

**Comment by mmatyas** [comment]
This should be fixed now.
