### ISSUE TITLE
Weird Tileset Behavior

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [mmatyas/supermariowar#230]
Tileset changing now has weird properties
For example, if I change any of the tileset below in SMWExtended...
https://cdn.discordapp.com/attachments/329412615048658944/975167446518476880/unknown.png
...it carries onto Extended3 for some reason...
https://cdn.discordapp.com/attachments/329412615048658944/975167602278170654/unknown.png

**Comment by mmatyas** [comment]
Ok, should be fixed now!
