### ISSUE TITLE
cmake .. -G 'Unix Makefiles' -DUSE_SDL2_LIBS=1 error

### ISSUE THREAD

**Issue by greennick78** [mmatyas/supermariowar#232]
Hey so trying to compile the game and got up to "cmake .. -G 'Unix Makefiles' -DUSE_SDL2_LIBS=1" but every time i try i get this error

CMake Deprecation Warning at CMakeLists.txt:7 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Error at CMakeLists.txt:144 (message):
  It seems you've forgot to clone the dependencies; dependencies/enet is not
  a git repository.Please run `git submodule update --init` first.
Call Stack (most recent call first):
  CMakeLists.txt:152 (check_submodule_git)

CMake Warning (dev) at CMakeLists.txt:154 (add_subdirectory):
  The source directory

    C:/Users/[REDACTED]/Downloads/supermariowar/dependencies/enet

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:144 (message):
  It seems you've forgot to clone the dependencies;
  dependencies/yaml-cpp-noboost is not a git repository.Please run `git
  submodule update --init` first.
Call Stack (most recent call first):
  CMakeLists.txt:158 (check_submodule_git)

CMake Warning (dev) at CMakeLists.txt:162 (add_subdirectory):
  The source directory

    C:/Users/[REDACTED]/Downloads/supermariowar/dependencies/yaml-cpp-noboost

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

    SYSTEM:      Windows AMD64
    BUILD:       Release
    CC:          C:/msys64/mingw32/bin/cc.exe
    CXX:         C:/msys64/mingw32/bin/c++.exe
    C FLAGS:      -std=c99 -O3 -s -fno-strict-aliasing -fexceptions -Wno-shadow
    CXX FLAGS:    -O3 -s -std=gnu++11 -Wtype-limits -Wsign-compare -Wignored-qualifiers -Wuninitialized -Wlogical-op -Wshadow -Winit-self -Wno-narrowing -fno-strict-aliasing -fexceptions -Wno-shadow -fvisibility-inlines-hidden
    LD FLAGS:     -static-libgcc -static-libstdc++
    DEFINITIONS: USE_SDL2;PNG_SAVE_FORMAT;NDEBUG;SMW_DATADIR="C:/Program Files (x86)/smw/data"
-- Configuring incomplete, errors occurred!
See also "C:/Users/[REDACTED]/Downloads/supermariowar/CMakeFiles/CMakeOutput.log".

i cant figure out what to do here at this point.

**Comment by mmatyas** [comment]
Hi, the error says:

```
It seems you've forgot to clone the dependencies; dependencies/enet is not
a git repository. Please run git submodule update --init first.
```
```
It seems you've forgot to clone the dependencies; dependencies/yaml-cpp-noboost is not
a git repository. Please run git submodule update --init first.
```

So it seems you haven't cloned the dependencies. As the message says, you can do that by running `git submodule update --init`.

**Comment by greennick78** [comment]
alright i figured it out, the error had nothin to do with anything here, turns out im just a dumbass and downloaded the github instead of using git clone, this was cause i tried using git clone after figuring out you were meant to do that and after typing the command correctly i kept getting and error, turns out its cause i did this after i downloaded the github version and it couldnt clone anything due to the directory having files already.

**Comment by greennick78** [comment]
new issue, trying to run the program pops up with "the code execution cannot proceed because [INSERT FILE.dll] was not found. Reinstalling the program may fix this problem"

these files are, libwinpthread-1.dll, SDL2.dll, SDL2_image.dll, and SDL2_mixer.dll. I did all the instructions again and yet still get this error.

**Comment by mmatyas** [comment]
To run any executable, all of the DLLs it depends on must be somewhere where the system (ie. Windows) finds it. On Windows, often the most accessible location is the directory of the EXE, ie. you can fix this by copying the required DLLs next to the game.
