### ISSUE TITLE
Music in game not working

### ISSUE THREAD

**Issue by greennick78** [mmatyas/supermariowar#234]
a strange thing is, even after adding dll's that the original mario war required to run, there still is no music, but there are sfx

**Comment by mmatyas** [comment]
Hm, do you see any errors on the log?

**Comment by greennick78** [comment]
im not getting any log in game and if you're talking about the log while building still no.

**Comment by greennick78** [comment]
*its specifically the level, world, and menu music by the way

**Comment by mmatyas** [comment]
Oh, I'm thinking about the game log; depending on how you've built it, it should either show up automatically if you start the game from the command line, otherwise you can use the `--debug` command line argument to show it.

**Comment by mmatyas** [comment]
Closing this due to lack of information. Feel free to comment if the issue still persists!
