### ISSUE TITLE
Super Mario War get stuck while loading

### ISSUE THREAD

**Issue by M0REKZ** [mmatyas/supermariowar#238]
Im on MacOS 13.2.1, arm64, i built the game but get stuck at here: 

<img width="752" alt="screen" src="https://user-images.githubusercontent.com/60852359/222519552-175367b3-907e-475d-a031-6da4ab4da041.png">

terminal output:

`Last login: Thu Mar  2 15:02:52 on ttys000
/Users/USER/Laboratorio/supermariowar/build/Binaries/Release/smw ; exit;    
USER@XXX-USER ~ % /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/smw ; exit;
objc[5999]: Class METAL_RenderData is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcc38) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5288). One of the two will be used. Which one is undefined.
objc[5999]: Class METAL_TextureData is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcc88) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b52d8). One of the two will be used. Which one is undefined.
objc[5999]: Class SDLApplication is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fc800) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5300). One of the two will be used. Which one is undefined.
objc[5999]: Class SDLAppDelegate is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fc850) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5350). One of the two will be used. Which one is undefined.
objc[5999]: Class SDLOpenGLContext is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fc990) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b53a0). One of the two will be used. Which one is undefined.
objc[5999]: Class SDL_cocoametalview is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fc940) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b53f0). One of the two will be used. Which one is undefined.
objc[5999]: Class SDLTranslatorResponder is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fc8c8) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5468). One of the two will be used. Which one is undefined.
objc[5999]: Class SDLMessageBoxPresenter is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fc8f0) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5490). One of the two will be used. Which one is undefined.
objc[5999]: Class SDL_ShapeData is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fca08) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5508). One of the two will be used. Which one is undefined.
objc[5999]: Class SDL_CocoaClosure is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fca58) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5558). One of the two will be used. Which one is undefined.
objc[5999]: Class SDL_RumbleMotor is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fccb0) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5580). One of the two will be used. Which one is undefined.
objc[5999]: Class SDL_RumbleContext is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcd00) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b55d0). One of the two will be used. Which one is undefined.
objc[5999]: Class SDL_WindowData is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcaf8) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5648). One of the two will be used. Which one is undefined.
objc[5999]: Class SDLWindow is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcb20) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5670). One of the two will be used. Which one is undefined.
objc[5999]: Class Cocoa_WindowListener is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcb48) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5698). One of the two will be used. Which one is undefined.
objc[5999]: Class SDLView is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcbc0) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5710). One of the two will be used. Which one is undefined.
objc[5999]: Class SDL_VideoData is implemented in both /opt/homebrew/Cellar/sdl2/2.26.3/lib/libSDL2-2.0.0.dylib (0x1057fcaa8) and /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x1056b5788). One of the two will be used. Which one is undefined.
-------------------------------------------------------------------------------
 Super Mario War 2.0
-------------------------------------------------------------------------------

---------------- startup ----------------
[gfx] SDL 2.26.1 loaded.
[gfx] SDL_image 2.6.3 loaded.
[gfx] Renderer: metal, accelerated
[gfx] Game window initialized (640x480, 32bpp)
[sfx] SDL_Mixer 2.6.3 initialized.
[net] ENet 1.3.13 initialized.
[net][warning] Could not open servers.yml, using default values.
[net] Network system initialized.

---------------- loading ----------------
Could not open /Users/USER/Library/Preferences/.smw/options.bin: No such file or directory
loading font /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_font_small.png ... done
loading font /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_font_large.png ... done
loading sprite (mode 3) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_background.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_smw.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_version.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/splash_credits.png...done
load /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/music/game/Standard/Menu/menu.ogg...
loading sprite (mode 3) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_shade.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/scoreboard.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_slider_bar.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_plain_field.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_player_select.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_dialog.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_map_filter.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_match_select.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_vertical_arrows.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_mode_small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_mode_large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/dialog.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/dialog_button.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/tournament_background.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/tournament_powerup_splash.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/player_select_background.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/player_select_ready.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_selectfield.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_selectfield_disabled.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_map_flags.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/tour_markers.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_boxed_numbers.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/game_countdown_numbers.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_warp_preview.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_warp_thumbnail.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_mapitems_preview.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_mapitems_thumbnail.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/menu/menu_announcement_icons.png...done
Loading sprite (mode 2) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/leveleditor/leveleditor_platformstarttile.png ...done
Loading sprite (mode 2) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/leveleditor/leveleditor_selectedtile.png ...done
Loading sprite (mode 2) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/leveleditor/leveleditor_platform_path.png ...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_background.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/preview/world_background.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_foreground.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/preview/world_foreground.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_foreground_special.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/preview/world_foreground_special.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_paths.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/preview/world_paths.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_vehicles.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/preview/world_vehicles.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_powerups.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_item_popup.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_powerupssmall.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_bonusplace.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/world/world_bonushouse.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Expanded/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Expanded/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Expanded/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Expanded2/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Expanded2/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Expanded2/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1Extended/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1Extended/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1Extended/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended4/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended4/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended4/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended3/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended3/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended3/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended2/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended2/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended2/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Classic/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Classic/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/Classic/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB2Extended/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB2Extended/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB2Extended/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorld/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorld/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorld/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SuperMarioWorldExtended/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB2Extended2/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB2Extended2/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB2Extended2/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB3Extended/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB3Extended/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB3Extended/small.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1Extended2/large.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1Extended2/medium.png...done
loading sprite (mode 1) /Users/USER/Laboratorio/supermariowar/build/Binaries/Release/data/gfx/packs/Classic/tilesets/SMB1Extended2/small.png...done`

**Comment by M0REKZ** [comment]
[spoiler][/spoiler] is missing on github :(

**Comment by M0REKZ** [comment]
forgot, was my bad

**Comment by lacerdamarcelo** [comment]
How did you solve this issue?

**Comment by M0REKZ** [comment]
Cant remember, but i think it was because i had 2 sdl installations, one as a framework and one through homebrew
