### ISSUE TITLE
Segfault during shutdown (SDL2, Linux KMS/DRM video driver)

### ISSUE THREAD

**Issue by cmitu** [mmatyas/supermariowar#258]
Hi @mmatyas,

 while testing _Super Mario War_ on RetroPie (RaspiOS 12 _bullseye_) I noticed that there's a `Segmentation fault` error that shows up during program shutdown (after the shutdown message is printed). This seemed fairly familiar and similar to [this SDL issue](https://github.com/libsdl-org/SDL/issues/3184)).

This issue has been known to bite other programs - see [here](https://github.com/dosbox-staging/dosbox-staging/issues/336) or [here](https://github.com/drfrag666/gzdoom/pull/10).

I'm not familiar with the codebase to suggest a fix, just noted that removing the `atexit` handler from [here](https://github.com/mmatyas/supermariowar/blob/a61122bcb3b64225cd6ff26451c415e2631291fa/src/common/gfx/gfxSDL.cpp#L64) does fix the segfault crash when exiting the game.

**Comment by mmatyas** [comment]
Interesting! Could you check if https://github.com/mmatyas/supermariowar/pull/259 fixes the issue?

**Comment by cmitu** [comment]
Yes, #259 works - no more Segfaults on exit. Thank you !
