### ISSUE TITLE
Mode settings display is broken

### ISSUE THREAD

**Issue by AtomicLugia** [mmatyas/supermariowar#262]
In the most recent version from Nov 23, in the Single Game Menu, the Settings for the Mode are displayed weirdly. It shows the value like 2-3 times in a row or is completly broken.
![grafik](https://github.com/mmatyas/supermariowar/assets/60356606/682d4420-ba4d-4dc4-ae8e-73d922ba1a2d)
![grafik](https://github.com/mmatyas/supermariowar/assets/60356606/4f95cbda-0f3d-4a22-8b13-e00f69f67af5)
![grafik](https://github.com/mmatyas/supermariowar/assets/60356606/7a8394d0-f4f7-4fbb-ac13-87dcc96152de)

**Comment by mmatyas** [comment]
Thanks for the report, will look into it!

**Comment by AtomicLugia** [comment]
> Thanks for the report, will look into it!

You're welcome!

**Comment by mmatyas** [comment]
Ok, this should be fixed now!
