### ISSUE TITLE
Question: is there any public server for smw?

### ISSUE THREAD

**Issue by Aryangh1379** [mmatyas/supermariowar#266]
Hi, thanks for your hard work, I love Super Mario War. My question: is there any public server for smw? or are you planning to make one? I searched and couldn't find any. thank you.

**Comment by mmatyas** [comment]
Hi! There are no official servers at the moment, as the network multiplayer is still quite experimental. If you're looking for players, the Discord channel might be the best place to ask around, then you can discuss whether to use the built-in netplay or some alternatives.
