### ISSUE TITLE
Level editor doesn't save

### ISSUE THREAD

**Issue by Shadowblitz16** [mmatyas/supermariowar#268]
The Level editor is saying it's saving but my map in not found.

I even moved the data folder to my home folder so there wouldn't be permission issues.

```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-18-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 15.0 GiB of RAM
Graphics Processor: RENOIR
```

**Comment by mmatyas** [comment]
Hi! If the level editor is unable to save the map, you should see some error message in the log (eg. when run from the terminal). Could you post the output of the editor?

**Comment by Shadowblitz16** [comment]
@mmatyas 
```
---------------- ready, steady, go! ----------------
entering level editor loop...
saving map /home/shadowblitz16/Documents/Games/SuperMarioWar/maps/test.map ... 
 ERROR: couldn't save map

 ERROR: Couldn't open map
loading sprite (mode 3) /home/shadowblitz16/Documents/Games/SuperMarioWar/gfx/packs/Classic/backgrounds/Land_Classic.png...done
saving map /home/shadowblitz16/Documents/Games/SuperMarioWar/maps/test.map ... 
 ERROR: couldn't save map

```

**Comment by mmatyas** [comment]
Yeah, hard to tell hat could be wrong, it does seem like a permission error. Not sure how the game was installed, but based on the path in your other issue (`/usr/local/games/smw-worldedit`), it seems to be a system package? You mentioned moving the data folder, but are you sure the files and subdirectories have the proper ownership and permission settings?

**Comment by Shadowblitz16** [comment]
@mmatyas yep that was the issue. 
I recursivly changed permissions of the SuperMarioWar folder I moved everything too and the level now saves.

I will check if it fixes the world editor
