### ISSUE TITLE
The game doesn't access the menu

### ISSUE THREAD

**Issue by Magirus-Deutz** [mmatyas/supermariowar#279]
![image](https://github.com/mmatyas/supermariowar/assets/20948362/b22fc474-cd76-4a2b-8937-da674c49c08b)
Everytime gives an error. i can't pass the credit screen.

**Comment by mmatyas** [comment]
Thanks for the report! Could you describe which version is this exactly? Have you added any content other than what's bundled with the game, that might cause this?

**Comment by mmatyas** [comment]
Ok, I think I've managed to reproduce it, curiously this seems to only occur on Windows.

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest version. Thanks again!

**Comment by Magirus-Deutz** [comment]
Now, i can access the menu, but other pages are also broken
![image](https://github.com/mmatyas/supermariowar/assets/20948362/f1c4b612-7f2f-48b6-9a41-1f5948c009ad)

i added nothing, i unzipped it and ran it
