### ISSUE TITLE
Now, i can access the menu, but other pages are also broken

### ISSUE THREAD

**Issue by Magirus-Deutz** [mmatyas/supermariowar#282]
Now, i can access the menu, but other pages are also broken
![image](https://github.com/mmatyas/supermariowar/assets/20948362/f1c4b612-7f2f-48b6-9a41-1f5948c009ad)

i added nothing, i unzipped it and ran it

_Originally posted by @Magirus-Deutz in https://github.com/mmatyas/supermariowar/issues/279#issuecomment-2030408300_

**Comment by mmatyas** [comment]
Ok, I know where the error is for this one. Do you see any other crashing menu screens?

**Comment by mmatyas** [comment]
Ok, should be fixed now.
