### ISSUE TITLE
Add OSX support

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/supermariowar#29]
- [x] SMW builds for OSX
- [x] Playable offline
- [ ] Playable online: not tested yet, anyone?

**Comment by mmatyas** [comment]
Anyone would like to test if it works?

**Comment by mmatyas** [comment]
Confirmed building and running offline.

**Comment by pzerou** [comment]
@mmatyas - do you have a copy of the Mac OS X build you created to try on **10.9.5** (Mavericks)? 
Currently have the 1.8b2 build crashing on full-screen

**Comment by mmatyas** [comment]
I don't have the package, sorry; I don't have a Mac so I've asked one of my friends to build it. We used SDL2, and the game seemed to run fine.

**Comment by mmatyas** [comment]
I've asked my friend to try on OSX, fullscreen works fine. Looks like the problem was fixed since 1.8b2.

**Comment by pzerou** [comment]
@mmatyas -- Thanks for followup! Sounds like it's a me problem then. Is there a precompiled Mac OS X release, with complete build & launcher that I could instead rely on? 

I've instead been using this dated 1.8b2 package from 2009 for the resources package, etc -- which may be my problem:
http://72dpiarmy.supersanctuary.net/index.php?topic=10241.0

**Comment by mmatyas** [comment]
There are no proper releases for this repo yet, it's still under development.
I can't create Mac releases, but I'm pretty sure we can find someone to help with this once we reach the beta. Until then, you can always build the latest version manually, you just need the necessary development tools (Xcode, Homebrew).

**Comment by mmatyas** [comment]
There's now an automated MacOS build, see https://github.com/mmatyas/supermariowar/releases/tag/continuous
