### ISSUE TITLE
Map preview doesn't draw all tiles when using SDL2

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/supermariowar#30]
As reported here: https://github.com/mmatyas/supermariowar/issues/6#issuecomment-133637128
Only happens with SDL2 build; after changing maps, only the background and the breakable blocks get drawn.

**Comment by mmatyas** [comment]
Fixed!

**Comment by HerbFargus** [comment]
:D I will test this when I can.

**Comment by HerbFargus** [comment]
Can confirm that it works. it plays in slowmotion though on my raspberry pi though, sound is normal speed but the gameplay is maybe half the speed, not sure if its a memory thing or something specific to my pi, though I have no speed issues with the sdl1 builds on my pi.

**Comment by HerbFargus** [comment]
I tested on my linux mint desktop and had no slowdown so it has something to do with the pi. I don't know why as the sdl2 builds before it was fixed didn't have any speed issues.

**Comment by mmatyas** [comment]
Could you try a completely new build? The slowdown happened to me too, but a clean build fixed that.

**Comment by mmatyas** [comment]
The following patch fixed the issue for me on an Odroid board, can you try this on RPi? If this works, I'll add a build flag to force SW rendering.

```diff
diff --git a/src/common/gfx/gfxSDL.cpp b/src/common/gfx/gfxSDL.cpp
index e55f638..81b2c85 100644
--- a/src/common/gfx/gfxSDL.cpp
+++ b/src/common/gfx/gfxSDL.cpp
@@ -114,7 +114,7 @@ void GraphicsSDL::create_game_window(bool fullscreen)
     void GraphicsSDL::create_renderer()
     {
         sdl2_renderer = SDL_CreateRenderer(sdl2_window, -1,
-            SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
+            SDL_RENDERER_SOFTWARE | SDL_RENDERER_TARGETTEXTURE);
         if (!sdl2_renderer) {
             fprintf(stderr, "[gfx] Couldn't create renderer: %s\n", SDL_GetError());
             throw E_CREATE_RENDERER;
```

**Comment by HerbFargus** [comment]
I'll give it a test right now and see if it works

**Comment by mmatyas** [comment]
Fixed and running fast.
