### ISSUE TITLE
Suggestion: Add support for OGG loops

### ISSUE THREAD

**Issue by AtomicLugia** [mmatyas/supermariowar#326]
I found a tutorial for RPG Maker VX Ace, where you can add "LOOPSTART" and "LOOPLENGTH" to OGG files with Audacity. "LOOPSTART" and "LOOPLENGTH" are measured in samples. This would be pretty handy to make for example some SNES Mario music loop correctly and seamless.

Is this possible to be implemented into Super Mario War? Since it has support for OGG files.

**Comment by Magirus-Deutz** [comment]
ogg loops is already supported. use "loopstart" and "loopend".
i dont know what is that "LOOPLENGTH" but "loopend" command is working

**Comment by mmatyas** [comment]
I think this can be closed then.
