### ISSUE TITLE
Misc. alpha testing results

### ISSUE THREAD

**Issue by HerbFargus** [mmatyas/supermariowar#5]
#### -DUSE_SDL2_LIBS=1 (test with fullscreen as well)

FAILS: see pastebin (http://pastebin.com/nkCFTeEF)
More Failes: see Pastebin (http://pastebin.com/WR5fzfKG)

Fullscreen exits out (it is inconsequential on the retropie build as it is full screen regardless of the setting)

Needs depencies installed on the rpi2 first (taken from here: https://solarianprogrammer.com/2015/01/22/raspberry-pi-raspbian-getting-started-sdl-2/):
```
Potential Dependencies?:

(also you can try installing from the retropie setup script with 
cd RetroPie
sudo ./retropie_packages sdl2
)

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essential libfreeimage-dev libopenal-dev libpango1.0-dev libsndfile-dev libudev-dev libasound2-dev libjpeg8-dev libtiff5-dev libwebp-dev automake

Install SDL 2.0:

cd ~
sudo wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz
tar zxvf SDL2-2.0.3.tar.gz
cd SDL2-2.0.3 && mkdir build && cd build
../configure --disable-pulseaudio --disable-esd --disable-video-mir --disable-video-wayland --disable-video-x11 --disable-video-opengl --host=armv7l-raspberry-linux-gnueabihf 
make -j 4
sudo make install

Install smpeg2:

cd ~
sudo wget http://www.libsdl.org/projects/smpeg/release/smpeg2-2.0.0.tar.gz
tar zxvf smpeg2-2.0.0.tar.gz
cd smpeg2-2.0.0 && mkdir build && cd build
../configure
make -j 4
sudo make install

Install SDL 2.0 Mixer:

cd ~
sudo wget http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz
tar zxvf SDL2_mixer-2.0.0.tar.gz
cd SDL2_mixer-2.0.0 && mkdir build && cd build
../configure
make -j 4
sudo make install

Install SDL Image:

cd ~
sudo wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
tar zxvf SDL2_image-2.0.0.tar.gz
cd SDL2_image-2.0.0 && mkdir build && cd build
../configure
make -j 4
sudo make install

Starting the game:
in `/home/pi/.bashrc`
add
export LD_LIBRARY_PATH=/usr/local/lib
at the end
then
sudo reboot

cd /supermariowar/Build/Binaries/Releases
./smw ../../../data
```

#### test uppercase yml

Works with lower and upper case yml.

#### test old build with git checkout 61d15626adfff82d44e304ace3faab229ca250da

userdir/datadir/bindir

**Comment by HerbFargus** [comment]
Initial Netplay Issues:

- Music isn't Synced (not sure if it should be or not)
- Pause doesn't work (the windows shows up but nothing pauses
- Skins don't show up on the other player's build- it defaults to mario
- Can't use items (like fire flowers)

**Comment by Ronoh55** [comment]
One more issue possibly related to floating through blocks.

Sometimes when a player breaks a block the graphic for it remains on the other's screen, but it is inactive (i.e. You can jump/fall straight through it). Sometimes going through that block causes a small lag or "float" through the box.

**Comment by mmatyas** [comment]
Yeah, most of these are because it's still alpha. The following can be considered bugs though:

- Gamepad controls don't save: that's a bug, thanks!
- Fullscreen crashes on SDL2 build
- Sometimes one character freezes in place: could you tell more details?

**Comment by mmatyas** [comment]
To make the Issues easier to follow, I've moved the netplay-related comments here: #8

**Comment by mmatyas** [comment]
I'm closing this issue as it's been moved to #8.
