### ISSUE TITLE
 error: ‘out’ was not declared in this scope      ((char*)&out)[0] = ((char*)&tmp)[1];

### ISSUE THREAD

**Issue by tlosm** [mmatyas/supermariowar#57]
smw dont build and exit with this error
server build 

log attached
[log.txt](https://github.com/mmatyas/supermariowar/files/339798/log.txt)

**Comment by mmatyas** [comment]
Thanks! I'm surprised this wasn't picked up by any of the automatic builds... anyway, this should be fixed now by aa756687fd102e35073d220c7e392b8baaeb9256.

**Comment by tlosm** [comment]
Confirmed build and works
