### ISSUE TITLE
Bugs not related to netplay functionality

### ISSUE THREAD

**Issue by Ronoh55** [mmatyas/supermariowar#6]
All of these seem random per match as I demonstrated in the video with the same match settings the bug appeared some times, and not others. 

~~-Getting lost in a pipe warp. Enter one end and never return.~~
~~-Items not working (boomerang, throwing bombs, fire flower, etc)~~
~~-Items not having limitations (2 fireballs/boomerangs on screen at once was intended limit)~~
Fixed!
Video of bugs:
https://youtu.be/Mhfkoupt_bs

**Comment by HerbFargus** [comment]
- Controls not saving
- SDL2 fullscreen freeze

**Comment by Ronoh55** [comment]
Pause text coordinates in source: https://github.com/mmatyas/supermariowar/blob/master/src/smw/GSGameplay.cpp#L1198

In theory tweaking this should be able to fix the text offset.
I plan on testing shortly.

**Comment by Cyantext** [comment]
I have a video where the player enters a pipe but does return after roughly 10 seconds. Check it out here https://www.youtube.com/watch?v=SU9Yyj8p2aE

**Comment by HerbFargus** [comment]
map thumbnails not showing platforms but they show in game:

![img_20150821_232506](https://cloud.githubusercontent.com/assets/10035308/9422677/36ee64b8-485c-11e5-9c1b-f4bb1cbdfa15.jpg)
![img_20150821_232528](https://cloud.githubusercontent.com/assets/10035308/9422678/396adce4-485c-11e5-932b-c947c4aa74bb.jpg)

**Comment by HerbFargus** [comment]
Menu Graphics, World Graphics, and Game Graphics not switching from classic to retro. I can select retro but nothing changes in the game. They also dont work with any other folders I added.

**Comment by mmatyas** [comment]
The graphics pack loading should be fixed now - please test if you still have the problem.

**Comment by Ronoh55** [comment]
Confirming that graphics packs are fixed.

**Comment by Ronoh55** [comment]
Map pieces carry over into other maps. Video shows in more detail. https://youtu.be/OT4Kdk233vw

**Comment by mmatyas** [comment]
Map pieces carry over into other maps. - Fixed!

I'm closing this issue, except the SDL2 bug (#30) all of them are now fixed. If you still find bugs, feel free to open an issue.
