### ISSUE TITLE
I could help....

### ISSUE THREAD

**Issue by monkeyman4412** [mmatyas/supermariowar#61]
I could probably help update smw for wii, and now since we have the vast majority of the wiiu under our belt, I could attmpt to make a port for wii and wiiu, A UPDATED, port... but I don't know, best of luck.

**Comment by mmatyas** [comment]
I don't have a Wii/WiiU for testing, but if you manage to port it or find some bugs, feel free to share it here or at [the forum](http://72dpiarmy.supersanctuary.net/)!
