### ISSUE TITLE
Same name, different author

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [mmatyas/supermariowar#72]
I want to request a bug that fixes the maps not be shown when they have the same name, but different authors... so you can show both.

Skins with same name but different authors show up without problem, so.

**Comment by mmatyas** [comment]
Ok done, will create a new release in a minute!

**Comment by mmatyas** [comment]
The new release is now available [here](https://github.com/mmatyas/supermariowar/releases/tag/v2.0-beta.1.1). I've only tested the Linux build though, so feel free to report if you have any troubles with it.
