### ISSUE TITLE
Can change resolution ?

### ISSUE THREAD

**Issue by springhack** [mmatyas/supermariowar#79]
I want to run in small LCD(320x240), but I saw this:

`
ScreenWidth = 640;
ScreenHeight = 480;
`

so can I change it and build to fit my LCD ?

**Comment by mmatyas** [comment]
Hi, unfortunately object sizes are somewhat hardcoded around the code, so changing these might lead to graphical glitches. Instead, I'd recommend building with SDL2 (`-DUSE_SDL2_LIBS=1`), where these values only control the internal resolution, but not the game window's size (it should stretch to fullscreen instead).

**Comment by springhack** [comment]
> Hi, unfortunately object sizes are somewhat hardcoded around the code, so changing these might lead to graphical glitches. Instead, I'd recommend building with SDL2 (`-DUSE_SDL2_LIBS=1`), where these values only control the internal resolution, but not the game window's size (it should stretch to fullscreen instead).

OK I will try this, thx

**Comment by mmatyas** [comment]
I suppose this can be closed.
