### ISSUE TITLE
World graphics are broken

### ISSUE THREAD

**Issue by AzureBerylBlue** [mmatyas/supermariowar#83]
![world](https://user-images.githubusercontent.com/53104010/65839437-93fc2000-e2db-11e9-92cb-80d459054cef.PNG)
It looks like it is using world_foreground.png instead of world_foreground_special.png
This image is from 1.8 beta 2:
![world2](https://user-images.githubusercontent.com/53104010/65839483-f2290300-e2db-11e9-8feb-5ef4e19a1c04.PNG)

**Comment by mmatyas** [comment]
Hm I wonder if that was intentional by one of the earlier developers?
