### ISSUE TITLE
Can I README to Korean ?

### ISSUE THREAD

**Issue by belocked** [mmatyas/supermariowar#97]
Hi guys. I'm common Korean developer, I read this README file.
And I thought these explanations in README file are a little bit difficult for Koreans who is not good at English. So can I add a Korean translated README file for those users?

**Comment by mmatyas** [comment]
Hi, well the problem with translated READMEs in general is that maintainers can't guarantee to keep them updated if the main one changes. Code repositories are mainly intended for developers, and with most programming languages being based on English, a developer have to understand it to a certain level in the first place to make it possible to work on it.

So I'm not sure how many readers would a translated README have (as opposed to eg. ingame text), but if you *do* make a translation I'm not against adding it either.

**Comment by belocked** [comment]
Oh, thanks for your prompt reply!! your reply is very helpful to me! As you say, there may not be many people to read it, but  I'm trying to translate it for novice developers like me.  Thanks!!!

**Comment by mmatyas** [comment]
Fixed by #102.
